Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2023-10, with the labels that each got.

#1 feat: introducing helmvm operator
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  api/v2alpha1/groupversion_info.go
  api/v2alpha1/installation_types.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/cluster.kurl.sh_installations.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_installations.yaml
  config/crd/patches/webhook_in_installations.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/installation_editor_role.yaml
  config/rbac/installation_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/cluster_v2alpha1_installation.yaml
  config/samples/kustomization.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  controllers/installation_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  main.go
  pkg/metrics/metrics.go
Labels: type::feature

#2 add dependabot and on-pr builds
  .github/dependabot.yml
  .github/workflows/pull-request.yaml
  api/v2alpha1/zz_generated.deepcopy.go
Labels: type::chore

#10 chore: renaming kurl.sh to replicated.com
  Makefile
  PROJECT
  api/v1beta1/groupversion_info.go
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_installations.yaml
  config/crd/patches/webhook_in_installations.yaml
  config/rbac/installation_editor_role.yaml
  config/rbac/installation_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/embeddedcluster_v1beta1_installation.yaml
  config/samples/kustomization.yaml
  controllers/installation_controller.go
  controllers/suite_test.go
  main.go
Labels: type::chore

#11 feat: creates crd for the embedded cluster config
  PROJECT
  api/v1beta1/config_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_configs.yaml
  config/crd/patches/webhook_in_configs.yaml
  config/rbac/config_editor_role.yaml
  config/rbac/config_viewer_role.yaml
  config/samples/embeddedcluster_v1beta1_config.yaml
  config/samples/kustomization.yaml
  main.go
Labels: type::feature

#12 feat: create helm chart for operator crds
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
  Makefile
  charts/embedded-cluster-operator-crds/.helmignore
  charts/embedded-cluster-operator-crds/Chart.yaml.tmpl
  charts/embedded-cluster-operator-crds/templates/_helpers.tpl
  charts/embedded-cluster-operator-crds/templates/resources.yaml
  charts/embedded-cluster-operator-crds/values.yaml
  charts/embedded-cluster-operator/Chart.yaml.tmpl
Labels: type::feature

#14 chore: fix wrong username and password + tag name change
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
Labels: type::chore

#19 bug: fix rbac for the embedded operator chart
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-leader-election-rolebinding.yaml
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-metrics-service.yaml
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-proxy-rolebinding.yaml
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-rolebinding.yaml
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-serviceaccount.yaml
  charts/embedded-cluster-operator/values.yaml
Labels: bug::normal, type::bug

#20 bug: remove the v from the operator tag
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
Labels: bug::normal, type::bug
