Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2024-01, with the labels that each got.

#56 feat: do not report upgrade during installation
  controllers/installation_controller.go
Labels: type::feature

#57 Revert "feat: remove unused config overrides field"
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
Labels: type::feature

#58 feat: keeping only provided k0s config overrides
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
Labels: type::feature

#59 feat: add properties for k0s config
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::feature

#60 Revert "feat: add properties for k0s config"
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::feature

#55 feat: upgrade helm charts as part of cluster upgrade
  api/v1beta1/installation_types.go
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
  config/rbac/role.yaml
  controllers/installation_controller.go
  controllers/installation_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/release/release.go
Labels: type::feature

#63 update operator clusterrole in chart
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
Labels: type::feature

#62 fetch metadata.json and k0s files from replicated.app
  controllers/installation_controller.go
  pkg/release/release.go
Labels: type::feature

#64 bug: check for version in installation before reconciling helm charts
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#68 bug: invert drift check
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#69 allow specifying additional helm charts to be installed
  api/v1beta1/config_types.go
  api/v1beta1/installation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
  go.mod
Labels: type::feature

#77 bug: add watch for charts resources.
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
  config/rbac/role.yaml
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#76 helm chart reconciliation testing
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller_test.go
  pkg/release/release.go
Labels: type::chore

#78 reconcile vs the chart spec version if not present in status
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller_test.go
Labels: type::chore

#79 bug: installation object never gets set to Installed due to false positive chart drift check
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: bug::regression, type::bug

#80 feat: check value drift
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
Labels: type::feature

#82 bug: merge chart values before comparing
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: bug::normal, type::bug
