Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2024-05, with the labels that each got.

#160 add hardcoded disaster recovery labels to CRDs
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/kustomization.yaml
  config/crd/patches/labels_in_configs.yaml
  config/crd/patches/labels_in_installations.yaml
Labels: type::feature

#161 sort installations by name, not creation timestamp
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#163 add protected/dynamic values to charts before reconcile
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: type::feature

#164 Publish a list of pending charts as part of the installation status
  controllers/installation_controller.go
  controllers/installation_controller_test.go
  go.mod
  go.sum
Labels: type::feature

#168 feat: allow cluster config on a secret
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  controllers/installation_controller.go
  go.mod
  go.sum
Labels: type::feature

#169 bug: bump embedded-cluster-kinds dependency
  go.mod
  go.sum
Labels: bug::normal, type::bug

#170 bug: fix various issues with the reconcile
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
  controllers/installation_controller.go
  go.mod
  go.sum
Labels: bug::normal, type::bug

#173 update k0s import to v1.30, which includes a struct change
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::chore

#174 undo k0s update
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::chore

#175 Add in-cluster k0s logs collector
  charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Labels: type::feature

#181 Revert "Add in-cluster k0s logs collector"
  charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Labels: bug::regression, type::bug

#182 Add in cluster logs collector back, but with a different configmap name
  charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Labels: type::feature

#184 Add make command to push operator image to ttl.sh
  Makefile
Labels: type::chore

#186 pull artifacts with and without tls
  pkg/artifacts/artifacts.go
Labels: type::feature

#190 upgrade embedded-cluster-kinds to v1.2.4, downgrade k0s import to v1.28.8+k0s.0
  go.mod
  go.sum
Labels: type::chore

#191 update crds for isHighAvailability field
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::feature

#195 rename high availability field in installation object
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::feature

#197 feat: cleanup ha registry code
  controllers/installation_controller.go
  pkg/errors/errors.go
  pkg/registry/metadata.go
  pkg/registry/secrets.go
  pkg/registry/secrets_test.go
  pkg/registry/util.go
Labels: type::feature

#199 feat: fix ha registry s3 address
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
  controllers/installation_controller.go
  pkg/k8sutil/labels.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/seaweedfs.go
  pkg/registry/seaweedfs_test.go
  pkg/registry/seaweedfsconfig.go
  pkg/registry/secrets.go
  pkg/registry/secrets_test.go
  pkg/util/net.go
  pkg/util/net_test.go
Labels: type::feature

#198 Add support for HA admin-console
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller_test.go
Labels: type::feature

#200 feat: cleanup stuck stateful pods
  controllers/installation_controller.go
  pkg/openebs/openebs.go
  pkg/openebs/openebs_test.go
  pkg/registry/registry_test.go
  pkg/registry/seaweedfs_test.go
  pkg/registry/secrets_test.go
  pkg/testutils/testutils.go
Labels: type::feature

#202 feat: inject seaweedfs s3 endpoint in operator
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  pkg/registry/registry.go
  pkg/registry/seaweedfs.go
Labels: type::feature

#203 fix: missing registry tls since chart moved to BuiltinConfigs
  pkg/release/release.go
  pkg/release/release_test.go
Labels: type::feature
