Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2024-07, with the labels that each got.

#238 use IPs within custom service cidr range for registry and seaweedfs services
  controllers/helm.go
  controllers/installation_controller.go
  pkg/registry/registry.go
  pkg/util/cidr.go
Labels: type::feature

#239 chore: Use reimplimented types
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
  go.mod
  go.sum
  pkg/release/release.go
  pkg/release/release_test.go
Labels: type::chore

#218 feat: ability to upgrade the cluster
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
  Makefile
  charts/embedded-cluster-operator/.helmignore
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
  charts/embedded-cluster-operator/values.yaml.tmpl
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/k0s.go
  controllers/k0s_test.go
  go.mod
  go.sum
  main.go
  pkg/artifacts/artifacts.go
  pkg/artifacts/registry.go
  pkg/artifacts/upgrade.go
  pkg/artifacts/upgrade_test.go
  pkg/autopilot/autopilot.go
  pkg/charts/charts.go
  pkg/charts/charts_test.go
  pkg/cli/logging.go
  pkg/cli/migrate.go
  pkg/cli/root.go
  pkg/cli/upgrade.go
  pkg/k8sutil/chartHealth.go
  pkg/k8sutil/client.go
  pkg/k8sutil/ensure.go
  pkg/k8sutil/ensure_test.go
  pkg/metadata/airgap.go
  pkg/migrations/common.go
  pkg/migrations/registry.go
  pkg/registry/migrate.go
  pkg/upgrade/upgrade.go
  scripts/publish-helm-chart.sh
Labels: type::feature

#251 Use pointer when converting Helm configs
  go.mod
  go.sum
  pkg/upgrade/upgrade.go
Labels: type::feature

#250 feat: build operator image with chainguard
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
  .github/workflows/pull-request.yaml
  .gitignore
  Makefile
  charts/embedded-cluster-operator/values.yaml
  deploy/apko.tmpl.yaml
  deploy/melange.tmpl.yaml
Labels: type::feature

#252 fix: unify chainguard tooling
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
  .github/workflows/pull-request.yaml
  Makefile
  deploy/melange.tmpl.yaml
Labels: type::chore

#259 remove owner references from HA components
  .github/workflows/pull-request.yaml
  Makefile
  controllers/installation_controller.go
  deploy/apko.tmpl.yaml
  pkg/registry/labels.go
  pkg/registry/migrate.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/seaweedfs.go
  pkg/registry/seaweedfs_test.go
  pkg/registry/seaweedfsconfig.go
  pkg/registry/secrets.go
  pkg/registry/secrets_test.go
  pkg/registry/util.go
Labels: bug::normal, type::bug

#260 install apko before using it to login
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
Labels: type::chore

#265 fix: k8s upgrades not working in airgapped environments
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/pull-request.yaml
  controllers/installation_controller.go
  controllers/k0s.go
  pkg/upgrade/upgrade.go
Labels: bug::regression, type::bug
