Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2024-02, with the labels that each got.

#86 do not update charts if they are still being created
  api/v1beta1/installation_types.go
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: bug::normal, type::bug

#87 do not update charts in cluster if ec metadata does not contain charts
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: type::chore

#90 only update k0s cluster config object if helm charts have changed
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: bug::normal, type::bug

#91 include what charts are still pending in the status
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: type::chore

#93 do not detect drift from helm repo count changes
  controllers/helm.go
Labels: bug::normal, type::bug

#95 improve merge values test
  controllers/helm_test.go
Labels: type::chore

#99 charts are still applying if the values hash is not updated
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
Labels: type::feature

#102 feat: take the embedded version cluster into account
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
  controllers/installation_controller.go
Labels: type::feature

#110 Fix sorting Helm charts with double digit order numbers
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller_test.go
Labels: bug::normal, type::bug

#109 feat: add a default cluster support bundle
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml
  charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
  charts/embedded-cluster-operator/troubleshoot/host-support-bundle.yaml
Labels: type::feature

#111 feat: remove host collectors and analysers from the cluster
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml
  charts/embedded-cluster-operator/troubleshoot/host-support-bundle.yaml
Labels: type::feature

#112 feat: replace troubleshoot.io with troubleshoot.sh
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml
Labels: type::feature
