Repository replicatedhq/embedded-cluster-operator, pull requests merged in 2024-04, with the labels that each got.

#134 use images from the local artifact mirror in airgap updates
  controllers/installation_controller.go
Labels: type::feature

#135 include binary name in CRD
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  go.mod
  go.sum
Labels: type::feature

#136 bug: specify nodes in the airgap upgrade plan command
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#137 store k0s binary as 'k0s-upgrade'
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#138 bug: stop using plan id to index autopilot plans
  controllers/installation_controller.go
  go.mod
Labels: bug::normal, type::bug

#139 include installation name in images bundle filename to avoid collisions
  controllers/installation_controller.go
Labels: type::feature

#141 fix rename of embedded-cluster images file
  controllers/installation_controller.go
Labels: type::feature

#143 the job name we are looking up needs to match
  controllers/installation_controller.go
Labels: type::feature

#147 bug: fix missing artifact copy job and autopilot airgap command
  controllers/installation_controller.go
Labels: bug::normal, type::bug

#153 Add velero (and optional extensions in general) to embedded cluster
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  controllers/installation_controller_test.go
  go.mod
  go.sum
  pkg/release/release.go
Labels: type::feature

#154 go 1.22.0
  .github/workflows/deploy-helm-production.yaml
  .github/workflows/deploy-helm-staging.yaml
  .github/workflows/pull-request.yaml
  Dockerfile
  go.mod
Labels: type::chore

#155 update sigs.k8s.io/controller-runtime and k8s.io imports
  go.mod
  go.sum
Labels: type::chore

#156 feat: allow users to override addon values.yaml
  charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  controllers/helm.go
  controllers/helm_test.go
  controllers/installation_controller.go
  go.mod
  go.sum
Labels: type::feature

#159 add eco labels to support bundle configmap
  charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml
Labels: type::feature
